// Re-export all types from shared schema
export type {
  Clinic,
  InsertClinic,
  User,
  InsertUser,
  Patient,
  InsertPatient,
  Appointment,
  InsertAppointment,
  MedicalRecord,
  InsertMedicalRecord,
  AnamnesisQuestion,
  InsertAnamnesisQuestion,
  AnamnesisResponse,
  InsertAnamnesisResponse,
  Budget,
  InsertBudget,
  Treatment,
  InsertTreatment,
  BudgetItem,
  InsertBudgetItem,
  BudgetSummary,
  InsertBudgetSummary,
  TreatmentMovement,
  InsertTreatmentMovement,
} from "@/../../shared/schema";